### ISSUE TITLE
Straight to 1.0?

### ISSUE THREAD

**Issue by jrjohnson** [romulomachado/ember-cli-string-helpers#1]
Since these were extracted from the stable ember-composable-helpers shouldn't this library be at `1.0`? The current `0.0.2` designation makes me thing that the API is unstable and I shouldn't use this library.

**Comment by romulomachado** [comment]
That sounds reasonable. Will bump the version.

**Comment by romulomachado** [comment]
Closed by https://github.com/romulomachado/ember-cli-string-helpers/commit/ab9f82dfed833bd58a35a22abcee37d0708558d1.
