### ISSUE TITLE
Feature Request: Add tree shaking capabilities 

### ISSUE THREAD

**Issue by jcope2013** [romulomachado/ember-cli-string-helpers#2]
Similar to https://github.com/DockYard/ember-composable-helpers, add optional tree-shaking capabilities – you can specify which helpers to whitelist or blacklist using only or except within your ember-cli-build.js:

Example

```
 module.exports = function(defaults) {
  var app = new EmberApp(defaults, {
    'ember-composable-helpers': {
      only: ['truncate'],
      except: ['underscore']
    }
  }); 
```

**Comment by romulomachado** [comment]
Hey @jcope2013, thanks for the suggestion! `1.1.1` can be downloaded from npm now w/ tree shaking capabilities.

**Comment by jcope2013** [comment]
@romulomachado thanks!
