### ISSUE TITLE
Project build contains all "app exports" from ember-cli-string-helpers

### ISSUE THREAD

**Issue by bertdeblock** [romulomachado/ember-cli-string-helpers#294]
## Version
`v5.0.0`

## Steps to reproduce
- Create a new Ember project
- Install `ember-cli-string-helpers`
- Configure it to include only a single helper: e.g. `lowercase`

## Expected Behavior
`my-app.js` only includes the `lowercase` app export.

## Actual Behavior
`my-app.js` includes the app exports of all string helpers.

By "app export" I mean, the re-exports defined in this addon's `app` folder.
These can be filtered out as well using the `treeForApp` hook.

[Ember Composable Helpers example.](https://github.com/DockYard/ember-composable-helpers/blob/master/index.js#L34)

## But Why?
One of our projects uses an internal addon which ships its own `html-safe` helper.
Even though we've configured `ember-cli-string-helpers` to not include the `html-safe` helper, there's a conflict between the two because the `html-safe` app export of `ember-cli-string-helpers` is still included in the final build.

Of course, we've removed our own custom helper, because there's no point in reinventing the wheel, but I just wanted to share this issue (even though it's and edge case).

It would also save some bytes.

**Comment by romulomachado** [comment]
Closed with #315
