### ISSUE TITLE
Lowercase helper

### ISSUE THREAD

**Issue by NLincoln** [romulomachado/ember-cli-string-helpers#5]
I think it's pretty self-explanatory.

```hbs
{{lowercase 'ABC'}}
```
becomes `abc`

**Comment by Moxide** [comment]
... and 
```handlebars
{{uppercase 'abc' }} 
```

would be great too ;-)

**Comment by romulomachado** [comment]
Closed by #6.

`1.2.0` includes the new helpers (`lowercase` and `uppercase`) and can be downloaded from npm now.
